# Copyright (c) 2019 The cxkernel Authors. All rights reserved.
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT
# 
# @file   .gitpod.yml
# @author Kevin Dai \<kevindai02@outlook.com\>
# @date   Created on December 27 2019, 7:39 PM

image:
  file: Dockerfile
tasks:
  - init: mkdir logs && cd build && . ./scripts/install_prereq.sh
