# @Author: Kevin Dai
# @Date:   13-Aug-2017 08:00:35 PM
# @Email:  kevindai02@outlook.com
# @Project: Eurus OS
# @File:   .gitlab-ci.yml
# @Last modified by:   Kevin Dai
# @Last modified time: 2017-11-27T15:37:51-05:00

before_script:
  - apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
  - sudo apt-get update
  - cd /builds/lonelywanderer/LiquiDOS
  - chmod +x configure
  - sh ./configure
  - export PATH=$PATH:/root/barebones-toolchain/cross/x86_64/bin
  - sudo apt-get install grub-common --yes

stages:
  - build

buildproj:
  stage: build
  script:
  - ./configure --target=i686
  - make
  artifacts:
    paths:
    - bin/*.bin
    - bin/*.iso
    name: "EurusOS_${CI_COMMIT_REF_NAME}"
    when: on_success
